const Router = require('express')
const router = new Router()
const productRouter = require('./productRouter')
const genderRouter = require('./genderRouter')
const typeRouter = require('./typeRouter')
const userRouter = require('./userRouter')
const imageRouter = require('./imageRouter')
const propertyRouter = require('./propertyRouter')
const productInfoRouter = require('./productInfoRouter')
const catalogsRouter = require('./catalogsRouter')
const catalogsInfoRouter = require('./catalogInfoRouter')
const statusesRouter = require('./statusesRouter')
const cartRouter = require('./cartRouter')
const cartProductRouter = require('./cartProductRouter')
const profileRouter = require('./profileRouter')
const mailGunRouter = require('./mailGunRouter')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/gender', genderRouter)
router.use('/product', productRouter)
router.use('/images', imageRouter)
router.use('/property', propertyRouter)
router.use('/product-info', productInfoRouter)
router.use('/catalogs', catalogsRouter)
router.use('/catalogs-info', catalogsInfoRouter)
router.use('/statuses', statusesRouter)
router.use('/cart', cartRouter)
router.use('/cart-products', cartProductRouter)
router.use('/profile', profileRouter) 
router.use('/email', mailGunRouter) 

module.exports = router